import datetime
from typing import Optional

from sqlalchemy import JSON, Date, DateTime, ForeignKey, Numeric, String, Time
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TenantOwnedMixin, TimestampMixin, UUIDPKMixin

BILL_RUN_STATUSES = ("pending", "generating", "completed", "failed")
PAYMENT_METHODS = ("e_transfer", "card", "bank_transfer", "cash", "cheque", "credit_note", "debit_note")


class BillCycle(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """Workbook §18."""

    __tablename__ = "bill_cycles"
    name: Mapped[str] = mapped_column(String(50), nullable=False)


class BillCyclePremise(Base):
    __tablename__ = "bill_cycle_premises"
    bill_cycle_id: Mapped[str] = mapped_column(ForeignKey("bill_cycles.id"), primary_key=True)
    premise_id: Mapped[str] = mapped_column(ForeignKey("premises.id"), primary_key=True)


class BillTemplate(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """Workbook §18 'Bill Template Mapping'. field_mapping selects which
    Bill Data Master fields (§21) appear on the rendered bill."""

    __tablename__ = "bill_templates"
    name: Mapped[str] = mapped_column(String(50), nullable=False)
    template_key: Mapped[str] = mapped_column(String(50), default="standard")  # which HTML template to render


class BillTemplateField(UUIDPKMixin, TenantOwnedMixin, Base):
    __tablename__ = "bill_template_fields"
    bill_template_id: Mapped[str] = mapped_column(ForeignKey("bill_templates.id"), nullable=False)
    field_key: Mapped[str] = mapped_column(String(100), nullable=False)  # from BILL_DATA_MASTER_FIELDS
    is_enabled: Mapped[bool] = mapped_column(default=True)
    sort_order: Mapped[int] = mapped_column(default=0)


class BillSchedule(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """Workbook §18. Generates Bill Runs (background job)."""

    __tablename__ = "bill_schedules"
    bill_cycle_id: Mapped[str] = mapped_column(ForeignKey("bill_cycles.id"), nullable=False)
    bill_template_id: Mapped[str] = mapped_column(ForeignKey("bill_templates.id"), nullable=False)
    recurring: Mapped[bool] = mapped_column(default=False)
    frequency: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    bill_start_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    bill_end_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    bill_generation_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    bill_generation_time: Mapped[datetime.time] = mapped_column(Time, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    is_active: Mapped[bool] = mapped_column(default=True)
    last_run_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(timezone=True), nullable=True)


class BillRun(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """No create form -- generated by BillSchedule (workbook §19)."""

    __tablename__ = "bill_runs"
    bill_schedule_id: Mapped[str] = mapped_column(ForeignKey("bill_schedules.id"), nullable=False)
    bill_cycle_id: Mapped[str] = mapped_column(ForeignKey("bill_cycles.id"), nullable=False)
    bill_template_id: Mapped[str] = mapped_column(ForeignKey("bill_templates.id"), nullable=False)
    consumer_count: Mapped[int] = mapped_column(default=0)
    bill_start_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    bill_end_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="pending")  # BILL_RUN_STATUSES
    error_message: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)


class Bill(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """One consumer's bill from a bill run. Stores the full computed Bill
    Data Master (§21) snapshot as JSON so history/PDF rendering never has
    to re-derive numbers that were true at generation time."""

    __tablename__ = "bills"

    bill_run_id: Mapped[str] = mapped_column(ForeignKey("bill_runs.id"), nullable=False)
    consumer_id: Mapped[str] = mapped_column(ForeignKey("consumers.id"), nullable=False)
    invoice_no: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    invoice_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    due_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    service_period_start: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    service_period_end: Mapped[datetime.date] = mapped_column(Date, nullable=False)

    usage: Mapped[float] = mapped_column(Numeric(14, 3), nullable=False)
    base_charge: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    service_charges_total: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    tax_amount: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    total_excl_tax: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    total_incl_tax: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)

    previous_outstanding: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    late_charges: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    credit_note: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    debit_note: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    total_outstanding: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)

    status: Mapped[str] = mapped_column(String(20), default="issued")  # issued|paid|partially_paid|overdue
    # Full computed Bill Data Master snapshot -- see app/services/billing_engine.py
    data: Mapped[dict] = mapped_column(JSON, nullable=False)
    pdf_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # Read-only: not used for writes (payments are inserted directly against
    # Payment.bill_id), just so `remaining_balance` below can be computed
    # without every caller writing its own payments-sum query. selectin
    # avoids N+1 when a whole bill list is serialized.
    payments: Mapped[list["Payment"]] = relationship("Payment", viewonly=True, lazy="selectin")

    @property
    def remaining_balance(self) -> float:
        """`total_outstanding` is a point-in-time snapshot of the running
        balance as of when this bill was generated (see
        billing_engine.compute_outstanding) and is intentionally never
        mutated after a payment -- the next bill's previous_outstanding is
        what threads payments forward. For display, callers actually want
        "how much of this specific bill is still unpaid right now", which
        this derives instead: total_outstanding minus payments recorded
        against this bill, floored at 0."""
        paid = sum((float(p.amount) for p in self.payments), 0.0)
        return max(float(self.total_outstanding) - paid, 0.0)


class BillLineItem(UUIDPKMixin, TenantOwnedMixin, Base):
    __tablename__ = "bill_line_items"
    bill_id: Mapped[str] = mapped_column(ForeignKey("bills.id"), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    kind: Mapped[str] = mapped_column(String(20), nullable=False)  # usage|service_charge|tax|credit|debit|late_fee
    amount: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)


class Payment(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    __tablename__ = "payments"
    bill_id: Mapped[str] = mapped_column(ForeignKey("bills.id"), nullable=False)
    consumer_id: Mapped[str] = mapped_column(ForeignKey("consumers.id"), nullable=False)
    amount: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    method: Mapped[str] = mapped_column(String(20), nullable=False)  # PAYMENT_METHODS
    paid_at: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    reference: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
