import datetime
from typing import Optional

from sqlalchemy import Boolean, Date, Float, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.base import TenantOwnedMixin, TimestampMixin, UUIDPKMixin

READ_TYPES = ("Manual", "Smart", "Photo")
ROUTE_READ_TYPES = ("Manual", "Smart", "Photo", "Estimated")
SCHEDULE_FREQUENCIES = ("Daily", "Weekly", "Monthly", "Quarterly")


class Meter(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """Workbook §12 fields."""

    __tablename__ = "meters"
    __table_args__ = (UniqueConstraint("tenant_id", "device_no", name="uq_meter_device_no_per_tenant"),)

    meter_no: Mapped[str] = mapped_column(String(30), nullable=False)
    device_no: Mapped[str] = mapped_column(String(30), nullable=False)
    utility_service_id: Mapped[str] = mapped_column(ForeignKey("utility_services.id"), nullable=False)
    read_type: Mapped[str] = mapped_column(String(20), nullable=False)  # READ_TYPES
    premise_id: Mapped[str] = mapped_column(ForeignKey("premises.id"), nullable=False)
    installation_date: Mapped[Optional[datetime.date]] = mapped_column(Date, nullable=True)
    latitude: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    longitude: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    unit: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    floor: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    meter_dial: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    is_assigned: Mapped[bool] = mapped_column(Boolean, default=False)  # true once linked to a Consumer


class Route(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """Workbook §13. Utility Service is multi-select -> route_utility_services."""

    __tablename__ = "routes"

    name: Mapped[str] = mapped_column(String(50), nullable=False)
    read_type: Mapped[str] = mapped_column(String(20), nullable=False)  # ROUTE_READ_TYPES
    premise_id: Mapped[str] = mapped_column(ForeignKey("premises.id"), nullable=False)


class RouteUtilityService(Base):
    __tablename__ = "route_utility_services"
    route_id: Mapped[str] = mapped_column(ForeignKey("routes.id"), primary_key=True)
    utility_service_id: Mapped[str] = mapped_column(ForeignKey("utility_services.id"), primary_key=True)


class RouteMeter(Base):
    """Meters assigned to a route -- drives the route's auto Meter Count."""

    __tablename__ = "route_meters"
    route_id: Mapped[str] = mapped_column(ForeignKey("routes.id"), primary_key=True)
    meter_id: Mapped[str] = mapped_column(ForeignKey("meters.id"), primary_key=True)


class ReadCycle(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """Workbook §14."""

    __tablename__ = "read_cycles"

    name: Mapped[str] = mapped_column(String(50), nullable=False)
    read_type: Mapped[str] = mapped_column(String(20), nullable=False)
    route_id: Mapped[str] = mapped_column(ForeignKey("routes.id"), nullable=False)


class ReadCycleUtilityService(Base):
    __tablename__ = "read_cycle_utility_services"
    read_cycle_id: Mapped[str] = mapped_column(ForeignKey("read_cycles.id"), primary_key=True)
    utility_service_id: Mapped[str] = mapped_column(ForeignKey("utility_services.id"), primary_key=True)


class MeterSchedule(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """Workbook §14 'Schedule'. Generates Meter Runs (background job)."""

    __tablename__ = "meter_schedules"

    read_cycle_id: Mapped[str] = mapped_column(ForeignKey("read_cycles.id"), nullable=False)
    recurring: Mapped[bool] = mapped_column(Boolean, default=False)
    frequency: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)  # SCHEDULE_FREQUENCIES
    start_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    due_days: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    description: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    last_run_at: Mapped[Optional[datetime.datetime]] = mapped_column(nullable=True)


class MeterRun(UUIDPKMixin, TimestampMixin, TenantOwnedMixin, Base):
    """No create form -- generated by MeterSchedule (workbook §14)."""

    __tablename__ = "meter_runs"

    meter_schedule_id: Mapped[str] = mapped_column(ForeignKey("meter_schedules.id"), nullable=False)
    run_date: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    premise_count: Mapped[int] = mapped_column(Integer, default=0)
    meter_count: Mapped[int] = mapped_column(Integer, default=0)
    readings_received: Mapped[int] = mapped_column(Integer, default=0)
    status: Mapped[str] = mapped_column(String(20), default="pending")  # pending|in_progress|completed
