"""phase2_8_domain_model

Revision ID: 5f044edc7246
Revises: 23f17ca03400
Create Date: 2026-08-17 00:00:32.227788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f044edc7246'
down_revision: Union[str, None] = '23f17ca03400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_meter_oems',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('utility_services', sa.String(length=255), nullable=False),
    sa.Column('highlights', sa.String(length=500), nullable=True),
    sa.Column('integration_resources', sa.String(length=500), nullable=True),
    sa.Column('links', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('utility_services',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bill_cycles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_cycles_tenant_id'), 'bill_cycles', ['tenant_id'], unique=False)
    op.create_table('bill_templates',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_templates_tenant_id'), 'bill_templates', ['tenant_id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('integration_configs',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('smart_meter_oem_id', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['smart_meter_oem_id'], ['smart_meter_oems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_tenant_id'), 'integration_configs', ['tenant_id'], unique=False)
    op.create_table('rates',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('basis', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_tenant_id'), 'rates', ['tenant_id'], unique=False)
    op.create_table('regions',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_tenant_id'), 'regions', ['tenant_id'], unique=False)
    op.create_table('tenant_services',
    sa.Column('utility_service_id', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'utility_service_id', name='uq_tenant_service')
    )
    op.create_index(op.f('ix_tenant_services_tenant_id'), 'tenant_services', ['tenant_id'], unique=False)
    op.create_table('vee_configs',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('utility_service_id', sa.String(), nullable=False),
    sa.Column('read_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vee_configs_tenant_id'), 'vee_configs', ['tenant_id'], unique=False)
    op.create_table('vee_rules',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('utility_service_id', sa.String(), nullable=False),
    sa.Column('read_type', sa.String(length=20), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vee_rules_tenant_id'), 'vee_rules', ['tenant_id'], unique=False)
    op.create_table('bill_schedules',
    sa.Column('bill_cycle_id', sa.String(), nullable=False),
    sa.Column('bill_template_id', sa.String(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('bill_start_date', sa.Date(), nullable=False),
    sa.Column('bill_end_date', sa.Date(), nullable=False),
    sa.Column('bill_generation_date', sa.Date(), nullable=False),
    sa.Column('bill_generation_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_cycle_id'], ['bill_cycles.id'], ),
    sa.ForeignKeyConstraint(['bill_template_id'], ['bill_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_schedules_tenant_id'), 'bill_schedules', ['tenant_id'], unique=False)
    op.create_table('bill_template_fields',
    sa.Column('bill_template_id', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_template_id'], ['bill_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_template_fields_tenant_id'), 'bill_template_fields', ['tenant_id'], unique=False)
    op.create_table('countries',
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_tenant_id'), 'countries', ['tenant_id'], unique=False)
    op.create_table('rate_tiers',
    sa.Column('rate_id', sa.String(), nullable=False),
    sa.Column('tier_from', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('tier_to', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_tiers_tenant_id'), 'rate_tiers', ['tenant_id'], unique=False)
    op.create_table('sub_categories',
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_categories_tenant_id'), 'sub_categories', ['tenant_id'], unique=False)
    op.create_table('tou_rates',
    sa.Column('rate_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tou_rates_tenant_id'), 'tou_rates', ['tenant_id'], unique=False)
    op.create_table('vee_config_rules',
    sa.Column('vee_config_id', sa.String(), nullable=False),
    sa.Column('vee_rule_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vee_config_id'], ['vee_configs.id'], ),
    sa.ForeignKeyConstraint(['vee_rule_id'], ['vee_rules.id'], ),
    sa.PrimaryKeyConstraint('vee_config_id', 'vee_rule_id')
    )
    op.create_table('vee_schedules',
    sa.Column('vee_config_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('repetition_interval', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vee_config_id'], ['vee_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vee_schedules_tenant_id'), 'vee_schedules', ['tenant_id'], unique=False)
    op.create_table('bill_runs',
    sa.Column('bill_schedule_id', sa.String(), nullable=False),
    sa.Column('bill_cycle_id', sa.String(), nullable=False),
    sa.Column('bill_template_id', sa.String(), nullable=False),
    sa.Column('consumer_count', sa.Integer(), nullable=False),
    sa.Column('bill_start_date', sa.Date(), nullable=False),
    sa.Column('bill_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_cycle_id'], ['bill_cycles.id'], ),
    sa.ForeignKeyConstraint(['bill_schedule_id'], ['bill_schedules.id'], ),
    sa.ForeignKeyConstraint(['bill_template_id'], ['bill_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_runs_tenant_id'), 'bill_runs', ['tenant_id'], unique=False)
    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('sub_category_id', sa.String(), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('billing_frequency', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)
    op.create_table('states',
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_tenant_id'), 'states', ['tenant_id'], unique=False)
    op.create_table('cities',
    sa.Column('state_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_tenant_id'), 'cities', ['tenant_id'], unique=False)
    op.create_table('plan_components',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('utility_service_id', sa.String(), nullable=False),
    sa.Column('rate_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_components_tenant_id'), 'plan_components', ['tenant_id'], unique=False)
    op.create_table('service_charges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('utility_service_id', sa.String(), nullable=True),
    sa.Column('charge_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_charges_tenant_id'), 'service_charges', ['tenant_id'], unique=False)
    op.create_table('zones',
    sa.Column('city_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_tenant_id'), 'zones', ['tenant_id'], unique=False)
    op.create_table('divisions',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_tenant_id'), 'divisions', ['tenant_id'], unique=False)
    op.create_table('areas',
    sa.Column('division_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_tenant_id'), 'areas', ['tenant_id'], unique=False)
    op.create_table('sub_areas',
    sa.Column('area_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('servicable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_areas_tenant_id'), 'sub_areas', ['tenant_id'], unique=False)
    op.create_table('premises',
    sa.Column('sub_area_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sub_area_id'], ['sub_areas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premises_tenant_id'), 'premises', ['tenant_id'], unique=False)
    op.create_table('bill_cycle_premises',
    sa.Column('bill_cycle_id', sa.String(), nullable=False),
    sa.Column('premise_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_cycle_id'], ['bill_cycles.id'], ),
    sa.ForeignKeyConstraint(['premise_id'], ['premises.id'], ),
    sa.PrimaryKeyConstraint('bill_cycle_id', 'premise_id')
    )
    op.create_table('meters',
    sa.Column('meter_no', sa.String(length=30), nullable=False),
    sa.Column('device_no', sa.String(length=30), nullable=False),
    sa.Column('utility_service_id', sa.String(), nullable=False),
    sa.Column('read_type', sa.String(length=20), nullable=False),
    sa.Column('premise_id', sa.String(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('meter_dial', sa.Float(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['premise_id'], ['premises.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'device_no', name='uq_meter_device_no_per_tenant')
    )
    op.create_index(op.f('ix_meters_tenant_id'), 'meters', ['tenant_id'], unique=False)
    op.create_table('routes',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('read_type', sa.String(length=20), nullable=False),
    sa.Column('premise_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['premise_id'], ['premises.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_tenant_id'), 'routes', ['tenant_id'], unique=False)
    op.create_table('consumers',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('contact_no', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('ssn', sa.String(length=11), nullable=False),
    sa.Column('id_document_url', sa.String(length=500), nullable=False),
    sa.Column('premise_id', sa.String(), nullable=False),
    sa.Column('service_address', sa.String(length=250), nullable=False),
    sa.Column('billing_address', sa.String(length=250), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('activation_date', sa.Date(), nullable=False),
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.Column('first_meter_reading', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('first_meter_reading_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('property_manager_user_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['premise_id'], ['premises.id'], ),
    sa.ForeignKeyConstraint(['property_manager_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_consumers_tenant_id'), 'consumers', ['tenant_id'], unique=False)
    op.create_table('read_cycles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('read_type', sa.String(length=20), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_read_cycles_tenant_id'), 'read_cycles', ['tenant_id'], unique=False)
    op.create_table('route_meters',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'meter_id')
    )
    op.create_table('route_utility_services',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('utility_service_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'utility_service_id')
    )
    op.create_table('bills',
    sa.Column('bill_run_id', sa.String(), nullable=False),
    sa.Column('consumer_id', sa.String(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('service_period_start', sa.Date(), nullable=False),
    sa.Column('service_period_end', sa.Date(), nullable=False),
    sa.Column('usage', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('base_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_charges_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_excl_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_incl_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_outstanding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_charges', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_note', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('debit_note', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_outstanding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_run_id'], ['bill_runs.id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_index(op.f('ix_bills_tenant_id'), 'bills', ['tenant_id'], unique=False)
    op.create_table('meter_schedules',
    sa.Column('read_cycle_id', sa.String(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['read_cycle_id'], ['read_cycles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_schedules_tenant_id'), 'meter_schedules', ['tenant_id'], unique=False)
    op.create_table('read_cycle_utility_services',
    sa.Column('read_cycle_id', sa.String(), nullable=False),
    sa.Column('utility_service_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['read_cycle_id'], ['read_cycles.id'], ),
    sa.ForeignKeyConstraint(['utility_service_id'], ['utility_services.id'], ),
    sa.PrimaryKeyConstraint('read_cycle_id', 'utility_service_id')
    )
    op.create_table('bill_line_items',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_line_items_tenant_id'), 'bill_line_items', ['tenant_id'], unique=False)
    op.create_table('meter_runs',
    sa.Column('meter_schedule_id', sa.String(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('premise_count', sa.Integer(), nullable=False),
    sa.Column('meter_count', sa.Integer(), nullable=False),
    sa.Column('readings_received', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meter_schedule_id'], ['meter_schedules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_runs_tenant_id'), 'meter_runs', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('consumer_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('meter_reading_imports',
    sa.Column('meter_run_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meter_run_id'], ['meter_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_reading_imports_tenant_id'), 'meter_reading_imports', ['tenant_id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.Column('meter_run_id', sa.String(), nullable=True),
    sa.Column('read_cycle_id', sa.String(), nullable=True),
    sa.Column('previous_reading', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('previous_reading_date', sa.Date(), nullable=True),
    sa.Column('current_reading', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_reading_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['meter_run_id'], ['meter_runs.id'], ),
    sa.ForeignKeyConstraint(['read_cycle_id'], ['read_cycles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_tenant_id'), 'meter_readings', ['tenant_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('import_id', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('meter_reading_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['meter_reading_imports.id'], ),
    sa.ForeignKeyConstraint(['meter_reading_id'], ['meter_readings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_tenant_id'), 'import_rows', ['tenant_id'], unique=False)
    op.create_table('validation_events',
    sa.Column('meter_reading_id', sa.String(), nullable=False),
    sa.Column('vee_rule_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meter_reading_id'], ['meter_readings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vee_rule_id'], ['vee_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_events_tenant_id'), 'validation_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_events_tenant_id'), table_name='validation_events')
    op.drop_table('validation_events')
    op.drop_index(op.f('ix_import_rows_tenant_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_meter_readings_tenant_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_meter_reading_imports_tenant_id'), table_name='meter_reading_imports')
    op.drop_table('meter_reading_imports')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_meter_runs_tenant_id'), table_name='meter_runs')
    op.drop_table('meter_runs')
    op.drop_index(op.f('ix_bill_line_items_tenant_id'), table_name='bill_line_items')
    op.drop_table('bill_line_items')
    op.drop_table('read_cycle_utility_services')
    op.drop_index(op.f('ix_meter_schedules_tenant_id'), table_name='meter_schedules')
    op.drop_table('meter_schedules')
    op.drop_index(op.f('ix_bills_tenant_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_table('route_utility_services')
    op.drop_table('route_meters')
    op.drop_index(op.f('ix_read_cycles_tenant_id'), table_name='read_cycles')
    op.drop_table('read_cycles')
    op.drop_index(op.f('ix_consumers_tenant_id'), table_name='consumers')
    op.drop_table('consumers')
    op.drop_index(op.f('ix_routes_tenant_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_meters_tenant_id'), table_name='meters')
    op.drop_table('meters')
    op.drop_table('bill_cycle_premises')
    op.drop_index(op.f('ix_premises_tenant_id'), table_name='premises')
    op.drop_table('premises')
    op.drop_index(op.f('ix_sub_areas_tenant_id'), table_name='sub_areas')
    op.drop_table('sub_areas')
    op.drop_index(op.f('ix_areas_tenant_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_divisions_tenant_id'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_zones_tenant_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_service_charges_tenant_id'), table_name='service_charges')
    op.drop_table('service_charges')
    op.drop_index(op.f('ix_plan_components_tenant_id'), table_name='plan_components')
    op.drop_table('plan_components')
    op.drop_index(op.f('ix_cities_tenant_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_states_tenant_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_plans_tenant_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_bill_runs_tenant_id'), table_name='bill_runs')
    op.drop_table('bill_runs')
    op.drop_index(op.f('ix_vee_schedules_tenant_id'), table_name='vee_schedules')
    op.drop_table('vee_schedules')
    op.drop_table('vee_config_rules')
    op.drop_index(op.f('ix_tou_rates_tenant_id'), table_name='tou_rates')
    op.drop_table('tou_rates')
    op.drop_index(op.f('ix_sub_categories_tenant_id'), table_name='sub_categories')
    op.drop_table('sub_categories')
    op.drop_index(op.f('ix_rate_tiers_tenant_id'), table_name='rate_tiers')
    op.drop_table('rate_tiers')
    op.drop_index(op.f('ix_countries_tenant_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_bill_template_fields_tenant_id'), table_name='bill_template_fields')
    op.drop_table('bill_template_fields')
    op.drop_index(op.f('ix_bill_schedules_tenant_id'), table_name='bill_schedules')
    op.drop_table('bill_schedules')
    op.drop_index(op.f('ix_vee_rules_tenant_id'), table_name='vee_rules')
    op.drop_table('vee_rules')
    op.drop_index(op.f('ix_vee_configs_tenant_id'), table_name='vee_configs')
    op.drop_table('vee_configs')
    op.drop_index(op.f('ix_tenant_services_tenant_id'), table_name='tenant_services')
    op.drop_table('tenant_services')
    op.drop_index(op.f('ix_regions_tenant_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_rates_tenant_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_integration_configs_tenant_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_bill_templates_tenant_id'), table_name='bill_templates')
    op.drop_table('bill_templates')
    op.drop_index(op.f('ix_bill_cycles_tenant_id'), table_name='bill_cycles')
    op.drop_table('bill_cycles')
    op.drop_table('utility_services')
    op.drop_table('smart_meter_oems')
    # ### end Alembic commands ###
